### ISSUE TITLE
problem with resource name

### ISSUE THREAD

**Issue by keulu-ing** [marmelab/ra-auth-acl#1]
Hi guys, nice lib but i have a strange behavior with it...

if i use the new `<ResourceWithPermission>` component, everything works fine except if i use a camelCased resource name.

`<ResourceWithPermission name="users" ... > // ok`
`<ResourceWithPermission name="adminUsers" ... > // broken. Menu, edit, showing, listing, nothing work.`

here is a sandbox for testing purpose.

`https://codesandbox.io/s/simple-5hp4k` (check the acl.js file for adjust.)

thanks

Edit :: After looking your component, i saw the problem... `const prefix = name.toLowerCase();`

**Comment by Kmaschta** [comment]
Thanks for reporting!

I'm not sure what's the best option: allow camelCase prefix, or lower the string at the check step tho.

**Comment by Kmaschta** [comment]
It should be fixed with `ra-auth-acl@0.1.1`

**Comment by keulu-ing** [comment]
nice. it works. thx
